commands: # commands that open the gui
  gui:
    - help
    - helpmenu
    - info
  books:
    help:
      - helpbook
    store:
      - store
      - donate
    map:
      - map
      - maps
    vote:
      - vote
    website:
      - website
      - site
      - web
    discord:
      - discord

messages:
  book-given: '<green>Added a book to your inventory!'

menu-name: 'Help Menu' # name of the help menu
book-author: 'SemiVanilla' # author of the books
book-name: 'Help Book'

links:
  store: 'https://store.semivanilla.com/'
  map: 'https://semivanilla.com/map'
  vote: 'https://semivanilla.com/vote'
  website: 'https://semivanilla.com/'
  discord: 'https://discord.gg/3WzZ3x6wGp'
  rules: 'https://semivanilla.com/rules'
book:
  help: # help book
    0:
      - 'Help Book'
      - ''
      - ''
      - 'Click <click:open_url:https://semivanilla.com>here</click> to go to the semivanilla website!'
      - ''
      - 'lorem ipsum dolt sit amet'
    1:
      - 'multiple pages'
      - 'abc'
      - 'def'
  store: # store book
    0:
      - '<gold><bold>Click <underlined><click:open_url:%store-link%>here</click></underlined> to open the store!</bold></gold>'
  map: # map book
    0:
      - '<gold><bold>Click <underlined><click:open_url:%map-link%>here</click></underlined> to open the map!</bold></gold>'
  vote: # vote book
    0:
      - '<gold><bold>Click <underlined><click:open_url:%vote-link%>here</click></underlined>!</bold></gold>'
  website: # website book
    0:
      - '<gold><bold>Click <underlined><click:open_url:%website-link%>here</click></underlined> to open the website!</bold></gold>'
  discord: # discord book
    0:
      - '<gold><bold>Click <underlined><click:open_url:%discord-link%>here</click></underlined> to join the discord!</bold></gold>'
  rules: # rules book
    0:
      - '<gold><bold>Click <underlined><click:open_url:%rules-link%>here</click></underlined> to open the rules page!</bold></gold>'
